version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - SA_PASSWORD=bank
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"

  bank:
    image: bank
    build:
      context: .
      dockerfile: Dockerfile

  